# Generated by Django 6.0.4 on 2026-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driver_booking_pickup_time_booking_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
